# MODI 연결
CONNECT_WAIT_SEC = 2

# IMU 움직임 감지 
MOTION_THRESHOLD = 5
MOTION_COUNT_REQUIRED = 3
BOTHER_INTERVAL_SEC = 4.0

# ToF 거리 감지 
TOF_MIN_DISTANCE = 2
TOF_MAX_DISTANCE = 30
TOF_COUNT_REQUIRED = 3

# 기분 입력
MOOD_MAX = 100

# 루프 타이밍
LOOP_SLEEP_SEC = 0.05
BUTTON_RELEASE_SLEEP_SEC = 0.01
REFRESH_TIME_SEC = 10

# 부저
BEEP_FREQ = 523
BEEP_VOLUME = 30
BEEP_ON_SEC = 0.08
BEEP_OFF_SEC = 0.05
BEEP_COUNT = 3

# LED 색상
LED_BLUE = (0, 0, 255)
LED_YELLOW = (255, 255, 0)
LED_GREEN = (0, 255, 0)
LED_RED = (255, 0, 0)

COUNSEL_EXIT_WORDS = ("종료", "끝", "quit", "exit")
